<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
<?php
	$lid = $block->getOrderId();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());
?>
<script type="text/javascript" src="//cdn.searchspring.net/intellisuggest/is.min.js"></script>
<script type="text/javascript">
	try {
		IntelliSuggest.init({siteId:'70bbfe'});
		<?php foreach($order->getAllItems() as $_item): ?>
			IntelliSuggest.haveItem({sku:"<?php echo $_item->getSku(); ?>", qty:"1", price:"<?php echo $_item->getPrice() ?>"});
		<?php endforeach ?>
		IntelliSuggest.inSale();
	} catch(err) {}
</script>