<div data-content-type="row" data-appearance="contained" data-element="main">
<div style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;" data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner">
<div style="border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;" data-content-type="html" data-appearance="default" data-element="main" data-decoded="true">
<div class="container content footer">
<div class="row">
<div class="col-sm-6 col-lg-3 first-extra">
<div class="footer-block-1 footer-col">
<h4 class="hidden-title we">Nosotros</h4>
<div class="footer-col-content we">
<div class="footer-logo">
<div class="logoAfter">&nbsp;</div>
<strong class="logo"> <img class="mplazyload" style="display: block;" src="https://www.curricanes.com/media/logo/stores/1/curricanes-logo.png" alt="CURRICANES.COM" width="350"> </strong></div>
<div class="desc-footer">Contamos con el mayor catalogo en productos de pesca y arquería, enviamos pedidos a toda la república mexicana. CURRICANES.COM, Obsesión por tu pasión!!!</div>
<ul class="list-footer">
   <li><a target="_blank" href="#"><i class="fa fa-cc-visa"></i></a></li>
            <li><a target="_blank" href="#"><i class="fa fa-cc-mastercard"></i></a></li>
            <li><a target="_blank" href="#"><i class="fa fa-cc-paypal"></i></a></li>
<!--<li><a target="_blank" href="#"><i class="fa fa-cc-discover"></i></a></li>--> <!--<li><a target="_blank" href="#"><i class="fa fa-cc-stripe"></i></a></li>--></ul>
</div>
</div>
</div>
<div class="col-sm-4 col-lg-2">
<div class="footer-col">
<h4 class="info">Información</h4>
<div class="footer-col-content info">
<ul>
<li><a href="{{store url="about-us"}}">Nosotros</a></li>
<!--<li><a href="https://www.curricanes.com/customer-service">Servicio al Cliente</a></li>--> <!--<li><a href="https://www.curricanes.com/template-settings">Template Settings</a></li>--></ul>
<ul class="footer links">
<li class="nav item"><a href="{{store url="privacy-policy-cookie-restriction-mode/"}}">Aviso de Privacidad</a></li>
<li class="nav item"><a href="{{store url="search/term/popular/"}}">Términos de búsqueda</a></li>
<li class="nav item"><a href="{{store url="contact/"}}">Contáctanos</a></li>
<li class="nav item"><a class="newsletter-popup-link" href="https://www.curricanes.com/newsletter/manage/index/">Suscríbete a nuestro Boletín de Noticias</a></li>
</ul>
</div>
</div>
</div>
<div class="col-sm-4 col-lg-2">
<div class="footer-col">
<h4 class="purchase">Compra en linea</h4>
<div class="footer-col-content purchase">
<ul>
<li><a href="{{store url="shipping-delivery"}}">Formas de Envío</a></li>
<li><a href="{{store url="secure-payment"}}">Métodos de Pago</a></li>
<!--<li><a href="{{store url="support"}}">Support</a></li>-->
<li><a href="{{store url="guarantee"}}">Garantía de Producto</a></li>
<li><a href="{{store url="terms-conditions"}}">Términos y Condiciones</a></li>
</ul>
</div>
</div>
</div>
<div class="col-sm-4 col-lg-2">
<div class="footer-col">
<h4 class="myaccount">Mi Cuenta</h4>
<div class="footer-col-content myaccount">
<ul>
<li><a href="{{store url="customer/account/login/"}}">Ingresar</a></li>
<li><a href="{{store url="checkout/cart/"}}">Ver Carrito</a></li>
<li><a href="{{store url="wishlist/"}}">Lista de Deseos</a></li>
</ul>
</div>
</div>
</div>
<div class="col-sm-6 col-lg-3 last-extra">
<div class="footer-info footer-col">
<h4 class="contact">Contactanos</h4>
<div class="footer-col-content contact">
<ul class="list-contacts-footer">
<li><a href="#">Carretera 57 Km. 195, Zona Industrial<br>San Luis Potosi, SLP, 78395</a></li>
<li>Teléfonos: <a href="callto:018007372271">01 800 PESCAR1</a><br><a href="callto:4448248703">(444) 8248703</a></li>
<li>E-mail: <a href="#">ventas@curricanes.com</a></li>
<li>Horario: Lunes a Viernes de 9:00-14:00/16:00-18:30</li>
</ul>
<ul class="list-icon">
<li><a target="_blank" href="//www.facebook.com/curricanes/"><i class="fa fa-facebook"></i></a></li>
            <li><a target="_blank" href="//twitter.com/tweetCurricanes/"><i class="fa fa-twitter"></i></a></li>
       
            <li><a target="_blank" href="//www.instagram.com/curricanes_com/"><i class="fa fa-instagram"></i></a></li>

</ul>
</div>
</div>
</div>
</div>
<small class="copyright">
<span>©<!--script type="text/javascript">var mdate = new Date(); document.write(mdate.getFullYear());</script--> </span>
</small></div>
</div>
</div>
</div>