<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></head>
<?php if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in"
              data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <span class="not-logged-in"
              data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>

<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
<script> 
(function (o, c, t, a, d, e, s, k) { o.octadesk = o.octadesk || {}; s = c.getElementsByTagName("body")[0]; k = c.createElement("script"); k.async = 1; k.src = t + '/' + a + '?showButton=' + d + '&openOnMessage=' + e; s.appendChild(k); })(window, document, 'https://chat.octadesk.services/api/widget', 'printbagembalagens', true, true); </script><script>
//para identificar seus usuários você deve chamar esse método passando o nome e o email do usuário e opcionalmente informar o id de seu chat
//lembrando que isso é apenas um modelo teste. Você deve chamar esse método em seu site para efetuar o login. Você pode autenticar seu usuário em qualquer momento no fluxo do seu site.
function logar_chat(usuario) {
octadesk.chat.login({
name: usuario.name, // nome do seu usuário
email: usuario.email // email do seu usuário
});
};
</script>